name = "Beautiful Hugo"
license = "MIT"
licenselink = ""
description = "An adaptation of an adaptation"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
features = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
min_version = 0.48

[params]
    [author]
        name = "Denis Shatilov"
        homepage = "https://www.linkedin.com/in/dshatilov/"

# If Porting existing theme
[original]
    name = "halogenica"
    homepage = "https://halogenica.net"
    licenselink = "https://github.com/halogenica/Hugo-BeautifulHugo/blob/master/LICENSE"